# Tags: 7.0-alpine3.14-arm64v8, 7.0.0-alpha.1-alpine3.14-arm64v8
FROM mcr.microsoft.com/dotnet/nightly/runtime:7.0-alpine3.14-arm64v8
FROM mcr.microsoft.com/dotnet/nightly/runtime:7.0.0-alpha.1-alpine3.14-arm64v8
