# Tags: 6.0-alpine3.15-arm32v7, 6.0-alpine-arm32v7, 6.0.0-alpine3.15-arm32v7
FROM mcr.microsoft.com/dotnet/nightly/runtime:6.0-alpine3.15-arm32v7
FROM mcr.microsoft.com/dotnet/nightly/runtime:6.0-alpine-arm32v7
FROM mcr.microsoft.com/dotnet/nightly/runtime:6.0.0-alpine3.15-arm32v7
