# Tags: 7.0-nanoserver-1809, 7.0.0-alpha.1-nanoserver-1809
FROM mcr.microsoft.com/dotnet/nightly/runtime:7.0-nanoserver-1809
FROM mcr.microsoft.com/dotnet/nightly/runtime:7.0.0-alpha.1-nanoserver-1809
