# Tags: 7.0-bullseye-slim-amd64, 7.0.0-alpha.1-bullseye-slim-amd64
FROM mcr.microsoft.com/dotnet/nightly/runtime:7.0-bullseye-slim-amd64
FROM mcr.microsoft.com/dotnet/nightly/runtime:7.0.0-alpha.1-bullseye-slim-amd64
