# Tags: 7.0.0-alpha.1-bullseye-slim-arm32v7, 7.0-bullseye-slim-arm32v7
FROM mcr.microsoft.com/dotnet/nightly/runtime:7.0.0-alpha.1-bullseye-slim-arm32v7
FROM mcr.microsoft.com/dotnet/nightly/runtime:7.0-bullseye-slim-arm32v7
