# Tags: 6.0-bullseye-slim-amd64, 6.0.0-bullseye-slim-amd64
FROM mcr.microsoft.com/dotnet/nightly/runtime:6.0-bullseye-slim-amd64
FROM mcr.microsoft.com/dotnet/nightly/runtime:6.0.0-bullseye-slim-amd64
