# Tags: 3.1-alpine3.15, 3.1-alpine, 3.1.21-alpine3.15
FROM mcr.microsoft.com/dotnet/nightly/runtime:3.1-alpine3.15
FROM mcr.microsoft.com/dotnet/nightly/runtime:3.1-alpine
FROM mcr.microsoft.com/dotnet/nightly/runtime:3.1.21-alpine3.15
