# Tags: 6.0-cbl-mariner1.0-distroless-amd64, 6.0.0-cbl-mariner1.0-distroless-amd64
FROM mcr.microsoft.com/dotnet/nightly/runtime:6.0-cbl-mariner1.0-distroless-amd64
FROM mcr.microsoft.com/dotnet/nightly/runtime:6.0.0-cbl-mariner1.0-distroless-amd64
