# Tags: 5.0-alpine3.15-arm64v8, 5.0-alpine-arm64v8, 5.0.12-alpine3.15-arm64v8
FROM mcr.microsoft.com/dotnet/nightly/runtime:5.0-alpine3.15-arm64v8
FROM mcr.microsoft.com/dotnet/nightly/runtime:5.0-alpine-arm64v8
FROM mcr.microsoft.com/dotnet/nightly/runtime:5.0.12-alpine3.15-arm64v8
