# Tags: 5.0-alpine3.15-amd64, 5.0-alpine-amd64, 5.0.12-alpine3.15-amd64
FROM mcr.microsoft.com/dotnet/nightly/runtime:5.0-alpine3.15-amd64
FROM mcr.microsoft.com/dotnet/nightly/runtime:5.0-alpine-amd64
FROM mcr.microsoft.com/dotnet/nightly/runtime:5.0.12-alpine3.15-amd64
