# Tags: 7.0-alpine3.15-amd64, 7.0-alpine-amd64, 7.0.0-alpha.1-alpine3.15-amd64
FROM mcr.microsoft.com/dotnet/nightly/runtime:7.0-alpine3.15-amd64
FROM mcr.microsoft.com/dotnet/nightly/runtime:7.0-alpine-amd64
FROM mcr.microsoft.com/dotnet/nightly/runtime:7.0.0-alpha.1-alpine3.15-amd64
