# Tags: 6.0-nanoserver-ltsc2022, 6.0.0-nanoserver-ltsc2022
FROM mcr.microsoft.com/dotnet/nightly/runtime:6.0-nanoserver-ltsc2022
FROM mcr.microsoft.com/dotnet/nightly/runtime:6.0.0-nanoserver-ltsc2022
