# Tags: 7.0-cbl-mariner1.0-distroless-amd64, 7.0.0-alpha.1-cbl-mariner1.0-distroless-amd64
FROM mcr.microsoft.com/dotnet/nightly/runtime:7.0-cbl-mariner1.0-distroless-amd64
FROM mcr.microsoft.com/dotnet/nightly/runtime:7.0.0-alpha.1-cbl-mariner1.0-distroless-amd64
