# Tags: 7.0-bullseye-slim-arm64v8, 7.0.0-alpha.1-bullseye-slim-arm64v8
FROM mcr.microsoft.com/dotnet/nightly/runtime:7.0-bullseye-slim-arm64v8
FROM mcr.microsoft.com/dotnet/nightly/runtime:7.0.0-alpha.1-bullseye-slim-arm64v8
