# Tags: 5.0-alpine-arm32v7, 5.0-alpine3.15-arm32v7, 5.0.12-alpine3.15-arm32v7
FROM mcr.microsoft.com/dotnet/nightly/runtime:5.0-alpine-arm32v7
FROM mcr.microsoft.com/dotnet/nightly/runtime:5.0-alpine3.15-arm32v7
FROM mcr.microsoft.com/dotnet/nightly/runtime:5.0.12-alpine3.15-arm32v7
